language: java
script: mvn test

addons:
  sonarcloud:
    organization: "shibir07"
    token:
      secure: "" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
