language: java
dist: trusty
script: mvn test
addons:
  sonarcloud:
    organization: "shibir7"
    token:
      secure: "${var.token}" # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=myorg_myrepo


